version: '3.2'

services:
  db:
    image: postgres:15.2
    container_name: nimble_survey_web_db
    environment:
      - POSTGRES_DB=nimble_survey_web_development
      - POSTGRES_PASSWORD=postgres

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    container_name: nimble_survey_web_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  prism:
    image: stoplight/prism:4
    container_name: nimble_survey_web_prism
    command: 'mock -h 0.0.0.0 /docs/openapi/openapi.yml'
    volumes:
      - ./docs:/docs
    ports:
      - "4010:4010"

volumes:
  postgres_data:
  redis_data:
